# apiVersion: v1
# kind: Pod
# metadata:
#   name: test
#   labels: 
#     {{- include "common.labels" . | nindent 4 }}
# spec:
#   containers:
#   - name: nginx
#     image: nginx
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  containers:
  - name: nginx
    image: nginx


    
