apiVersion: v1
kind: Pod
metadata:
  name: multipod
  labels:
    app: javawebapp
spec:
  containers:
  - name: javawebappcontainer
    image: kishornandhu/tcs-demo
    ports:
    - containerPort: 80
  - name: nodeapp
    image: kishornandhu/nodeapp
    ports:
    - containerPort: 9981


---
apiVersion: v1
kind: Service
metadata:
  name: testsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 80
    name: java
  - port: 9981
    targetPort: 9981
    name: node