apiVersion: v1
kind: Pod
metadata:
  name: nodejs
  namespace: test-ns
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeappcontainer
      image: kishornandhu/nodeapp
      ports:
      - containerPort: 9981

---
apiVersion: v1
kind: Service
metadata:
  name: nodejssvc
  namespace: test-ns
spec:
  type: NodePort
  selector: 
    app: nodeapp
  ports:
  - port: 80
    targetPort: 9981