apiVersion: v1
kind: Service
metadata:
  name: app #name of the service
  namespace: test-ns
spec:
  #type: NodePort
  selector: #pod lables as selectors
    app: nginx
  ports:
  - port: 8080 #service port
    targetPort: 80  #container port

#pod -v1 service - v1