apiVersion: v1
kind: ReplicationController
metadata:
  name: javaapprc
  namespace: test-ns
spec:
  replicas: 2
  template:
    metadata:
      name: javapod
      labels:
        app: javaapp
    spec:
    containers:
    - name: javacontainer
      image: kishornandhu/tcs-demo
      ports:
      - containerPort: 80