apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebpp
  namespace: test-ns
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: samplewebpp
  template:
    metadata:
      name: samplewebppod
      labels:
        app: samplewebpp
    spec:
      containers:
        - name: mavenwebapp
          image: kishornandhu/maven-app
          ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
matadata:
  name: mavenapp-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
  - port: 80
    targetPort: 8080