# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CD with Maven

on:
  [workflow_dispatch]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  deploy:

    runs-on: Linux

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: update kubeconfig
      run: aws eks --region $AWS_REGION update-kubeconfig --name dev
    - name: Replace image tag in deployment file
      run: |
        TAG=${{ github.sha }}
        sed "s|TAG_PLACEHOLDER|$TAG|" k8s/deployment.yml > k8s/deployment-patched.yml

    - name: Deploy to EKS
      run: |
          cat k8s/deployment-patched.yml
          echo "==="
          cat k8s/deployment.yml
          kubectl apply -f k8s/deployment-patched.yml
          kubectl apply -f k8s/service.yml
